engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
  eslint:
    enabled: true
    config:
      ignore_warnings: true
    checks:
      import/extensions:
        enabled: false
ratings:
  paths:
    - "**.js"
