engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
  eslint:
    enabled: true
    config:
      ignore_warnings: true
    checks:
      complexity:
        enabled: true
      import/extensions:
        enabled: false
