engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
    exclude_paths:
      - "**.test.js"
  eslint:
    enabled: true
    config:
      ignore_warnings: true
    checks:
      import/extensions:
        enabled: false
  nodesecurity:
    enabled: false
ratings:
  paths:
    - "**.js"
